### ISSUE TITLE
Add printed versions to release

### ISSUE THREAD

**Issue by TomWheal** [srobo/competitor-booklet-2019#2]
I can't do it, however, it's probably worth adding the following to a release: 

[Booklet-Final.pdf](https://github.com/srobo/competitor-booklet-2019/files/3022954/Booklet-Final.pdf)
[flyer-Final.pdf](https://github.com/srobo/competitor-booklet-2019/files/3022955/flyer-Final.pdf)

[booklet-flyer-inDesign.zip](https://github.com/srobo/competitor-booklet-2019/files/3022964/booklet-flyer-inDesign.zip)

**Comment by RealOrangeOne** [comment]
You now _should_ have permission.
